version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Ejecutar script
          command: python script.py

workflows:
  version: 2
  build_and_test:
    jobs:
      - build