version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Instalar dependencias
          command: pip install --upgrade pip
      - run:
          name: Ejecutar pruebas
          command: python -m unittest test_app.py